name: Python Checks

on:
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint ruff black bandit pytype

    - name: Run Pylint
      run: |
        pylint QR\ Code\ Genrator/*.py
      continue-on-error: true

    - name: Run Ruff
      run: |
        ruff check QR\ Code\ Genrator/
      continue-on-error: true

    - name: Run Black
      run: |
        black --check QR\ Code\ Genrator/
      continue-on-error: true

    - name: Run Bandit
      run: |
        bandit -r QR\ Code\ Genrator/
      continue-on-error: true

    - name: Run Pytype
      run: |
        pytype QR\ Code\ Genrator/
      continue-on-error: true
